config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index'
  get 'home/index'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :images
  resources :ads

match ':controller(/:action(/:id(.:format)))' => 'home#show', via: [:get, :post]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/ad.rb
class Ad < ActiveRecord::Base
	has_many :images,:dependent => :destroy
	accepts_nested_attributes_for :images
    belongs_to :category
    validates :title, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :ads
  validates :name, presence: true, uniqueness: true
end

app/models/image.rb
class Image < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
    belongs_to :ad
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]

  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all
    @categories = Category.pluck(:name)
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
       @ad = Ad.find(params[:id]).images.all

  end

  # GET /ads/new
  def new
    @ad = Ad.new
    @post_attachment = @ad.images.build
    @category = Category.all
  end

  # GET /ads/1/edit
  def edit
    @category = Category.all
  end

respond_to do |format|
     if @post.save
       params[:post_attachments]['avatar'].each do |a|
          @post_attachment = @post.post_attachments.create!(:avatar => a, :post_id => @post.id)
       end
       format.html { redirect_to @post, notice: 'Post was successfully created.' }
     else
       format.html { render action: 'new' }
     end
   end


  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(ad_params)
    @ad.category_id = params[:catagory_id]

    respond_to do |format|
      if @ad.save
# WORKING.....
        params[:images]['avatar'].each do |a|
          @post_attachment = @ad.images.create!(:avatar => a, :ad_id => @ad.id)
        end

        format.html { redirect_to @ad, notice: 'Ad was successfully created.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)

        format.html { redirect_to @ad, notice: 'Ad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end
           # @ad = Ad.find(params[:id]).images.all


    # Never trust parameters from the scary internet, only allow the white list through.
 def ad_params
      params.require(:ad).permit(:title, images: [:id, :ad_id, :avatar])
   end
end
 # def ad_params
 #      params.require(:post).permit(:title, post_attachments_attributes: [:id, :ad_id, :avatar])
 #   end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
  # protect_from_forgery with: :exception
    rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	 @categories = Category.all.map(&:name)
  end

  def show
	logger.info"ssssssssssssssssssssssssssssss#{params[:s].inspect}"
  	@categories = Category.find_by_name(params[:s]).ads	
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:ad_id, :avatar)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/ads/_form.html.erb
<%= form_for(@ad) do |f| %>
  <% if @ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
      <% @ad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

    <div class="field">
    <%= f.label :category %><br>
   <%= select_tag "catagory_id", options_from_collection_for_select(@category, "id", "name")%>
  </div>


  <%= f.fields_for :images do |p| %>
     <div class="field">
       <%= p.label :avatar %><br>
       <%= p.file_field :avatar, :multiple => true, name: "images[avatar][]" %>
     </div>
     <%end%>
     <br>
  <div class="actions">
    <%= f.submit :class => 'btn btn-success'%>
  </div>
<% end %>

app/views/ads/edit.html.erb
<%- model_class = Ad -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ads/index.html.erb
<%- model_class = Ad -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ads.each do |ad| %>
      <tr>
        <td><%= link_to ad.id, ad_path(ad) %></td>
        <td><%= ad.title %></td>
        <td><%= ad.category_id %></td>
        <td><%=l ad.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_ad_path(ad), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      ad_path(ad),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_ad_path,
            :class => 'btn btn-primary' %>

app/views/ads/new.html.erb
<%- model_class = Ad -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ads/show.html.erb
   <% @ad.each do |image| %>
   <%= image_tag image.avatar_url, :size => "200x200" ,:class => 'img-circle' %> 
  <%end%>
 
<%#= params[:id]%>
<%#= @ad.inspect%><br><br><br>
<%= link_to 'Edit', edit_ad_path(params[:id]) ,:class =>'btn btn-success'%> |
<%= link_to 'Back', ads_path ,:class => 'btn btn-danger'%>
	

app/views/home/index.html.erb
<h3>Categories</h3>
    <div class="container" id="tourpackages-carousel">
      <div class="row">
    <% @categories.each do |ad| %>
        
      <form accept-charset="UTF-8" action="/home/show" method="post">
        <div class="col-xs-18 col-sm-6 col-md-3">
          <div class="thumbnail"> 
              <div class="caption">
                <h4><%= ad %></h4>
                <input type="hidden" name="s" value="<%=ad%>">
                <input type="submit" class="btn btn-info btn-xs" value="show">
            </div>
          </div>
        </div>
      </form>
    <% end %>
      </div><!-- End row -->
      
    </div><!-- End container -->

app/views/home/show.html.erb
<% @categories.each do |ads| %>
	<h1><%= ads.title %></h1>
	<% ads.images.each do |image| %>
		<%= image_tag image.avatar, :width => "200" %>
	<% end %>
	<br><br>
<% end %>

app/views/images/_form.html.erb
<%= form_for @image, :html => { :class => "form-horizontal image" } do |f| %>

    <% if @image.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @image.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :ad_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ad_id, :class => 'form-control' %>
    </div>
    <%= error_span(@image[:ad_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :avatar, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :avatar, :class => 'form-control' %>
    </div>
    <%= error_span(@image[:avatar]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            images_path, :class => 'btn btn-default' %>

<% end %>

app/views/images/edit.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/index.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:ad_id) %></th>
      <th><%= model_class.human_attribute_name(:avatar) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= link_to image.id, image_path(image) %></td>
        <td><%= image.ad_id %></td>
        <td><%= image_tag image.avatar ,:width => 200%></td>
        <td><%=l image.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_image_path(image), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      image_path(image),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_image_path,
            :class => 'btn btn-primary' %>

app/views/images/new.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/show.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:ad_id) %>:</strong></dt>
  <dd><%= @image.ad_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar) %>:</strong></dt>
  <dd><%= @image.avatar %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              images_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_image_path(@image), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              image_path(@image),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Task" %></title>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Task</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Ads", "/ads"  %></li>
            <li><%= link_to "Images", "/images"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>

          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

        <div id="user_nav">
          <% if user_signed_in? %>
            Signed in as <%= current_user.email %>.<br> Not you?<br>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete ,:class => 'btn btn-danger'%>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path,:class => 'btn btn-danger' %> &nbsp;&nbsp; <%= link_to "sign in", new_user_session_path ,:class => 'btn btn-primary'%>
          <% end %>
        </div>



      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>